version: "3.8"
services:
  streamlit:
    build: 
      context: ./streamlit
      dockerfile: .docker/Dockerfile
    image: dataviz/streamlit:0.0.1
    container_name: streamlitcont
    command: "streamlit run app.py"
    volumes:
      - "./streamlit:/streamlit"
    environment: 
      PYTHONUNBUFFERED: 'true'
    ports:
      - "8501:8501"

  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: andres
      MYSQL_DATABASE: datavizapp
    ports:
      - "3308:3306"
    volumes:
      - "./db:/db"
    restart: unless-stopped

  # admin:
  #   image: adminer
  #   ports:
  #     - "8080:8080"

  # services:

  # mysql-development:
  #   image: mysql:8.0.17
  #   environment:
  #     MYSQL_ROOT_PASSWORD: helloworld
  #     MYSQL_DATABASE: testapp
  #   ports:
  #     - "3308:3306"

  # admin:
  #   image: adminer
  #   ports:
  #     - "8080:8080"

  # db:
  #   image: mysql:8.0.2
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD 
  #     MYSQL_DATABASE: MYSQL_DATABASE

